
```{r}
hospital<-read.table("C:/Users/xchai/Desktop/Xiaomeng/488 Statistical Consultation/Individual Presentation/allhospital.txt", header=FALSE, sep=",",strip.white=TRUE, col.names = c("ZIP","HID","CITY","STATE", "BEDS","RBEDS","OUTV","ADM","SIR","SALESY","SALES12","HIP95","KNEE95","TH","TRAUMA","REHAB","HIP96","KNEE96","FEMUR96"))
#head(hospital)
#dim(hospital)

#4 States are chosen for further analysis
hosp<-hospital[hospital$STATE=="IL" | hospital$STATE=="IN" | hospital$STATE=="MI" | hospital$STATE=="WI",]
dim(hosp)
head(hosp)

#transformation
hosp$SALES<-ifelse(hosp$SALES12==0,"NA",log(1+hosp$SALES12))

hosp$BEDS<-sqrt(hosp$BEDS)
hosp$RBEDS<-sqrt(hosp$RBEDS)
hosp$HIP95<-sqrt(hosp$HIP95)
hosp$KNEE95<-sqrt(hosp$KNEE95)
hosp$HIP96<-log(1+0.01*hosp$HIP96)
hosp$KNEE96<-log(1+0.01*hosp$KNEE96)
hosp$FEMUR96<-log(1+0.01*hosp$FEMUR96)
hosp$OUTV<-log(1+0.001*hosp$OUTV)
hosp$ADM<-log(1+0.001*hosp$ADM)
hosp$SIR<-log(1+0.001*hosp$SIR)
```


**Factor analysis in two stages**
```{r}
dim(hosp)
names(hosp)
library(stats)
attach(hosp)
#stage 1 Factor Analysis
faset1<-subset(hosp,select=c(12,13,17:19))
fa1<-factanal(faset1,1, rotation="varimax", scores="Bartlett")
head(fa1$scores)
names(fa1)

#stage 2 Factor Analysis
faset2<-subset(hosp,select=c(5:9, 14:16))
fa2<-factanal(faset2,2, rotation="varimax", scores="Bartlett")
fa2
head(fa2$scores)
```

**PCA**
```{r}
pcaset1<-subset(hosp,select=c(12,13,17:19))
pcafit1<-princomp(pcaset1, cor=TRUE)
summary(pcafit1)
loadings(pcafit1) # pc loadings 
plot(pcafit1,type="lines") # scree plot 
#pcafit1$scores # the principal components
biplot(pcafit1)

pcaset2<-subset(hosp,select=c(5:9, 14:16))
pcafit2<-princomp(pcaset2, cor=TRUE)
summary(pcafit2)
loadings(pcafit2) # pc loadings 
plot(pcafit2,type="lines") # scree plot 
pcafit2$scores # the principal components
biplot(pcafit2)
```



```{r}
#merge FA scores into hosp--final dataset is'merghosp'
colnames(fa2$scores)<-c("Factor2", "Factor3")  

m1<-merge(hosp, fa1$scores, by="row.names")  
head(fa2$scores)
m2<-merge(hosp, fa2$scores, by="row.names")

merghosp<-merge(subset(m1, select=c(1:22)),subset(m2,select=c(1,22:23)),by="Row.names")
dim(merghosp)
```

**PAM**
```{r}
library(cluster)
attach(merghosp)
#plot(silhouette(pam(merghosp[,22:24],k=6)),main=paste("k = ", 6), do.n.k=FALSE)

#PAM
#p0<-pam(merghosp,4)
#summary(p0)
#str(si<-silhouette(p0))
#plot(si)

#silhouette width

## Use the silhouette widths for assessing the best number of clusters,

knumber <- numeric(20)
for (k in 2:20)
  {
  knumber[k] <- pam(merghosp[,22:24], k) $ silinfo $ avg.width
  }
k.best <- which.max(knumber)
cat("silhouette-optimal number of clusters:", k.best, "\n")

plot(1:20, knumber, type= "h", main = "PAM clustering assessment",
     xlab= "k  (# clusters)", ylab = "average silhouette width")
axis(1, k.best, paste("best",k.best,sep="\n"), col = "red", col.axis = "red")

#choose 5 clusters
k5<-pam(merghosp[,22:24], 5)$silinfo
k5$clus.avg.widths
k5$avg.width
detach(merghosp)
```

**CART using RPART**

```{r}
library(rpart)
attach(merghosp)

pred<-predict(rpart(SALES~Factor1+Factor2+Factor3, data=merghosp))
#summary(pred)
#table(pred)
#length(pred)

fit2<-rpart(SALES~Factor1+Factor2+Factor3, data=merghosp, control=rpart.control(cp=.001))

printcp(fit2)#cp table
plotcp(fit2)#plot cross-validation results

#prune tree
pfit2<-prune(fit2,cp=0.0029)
plot(pfit2,uniform=TRUE, main=" Pruned Regression Tree for Log(1+SALES12)")
text(pfit2, all=T, cex=0.6)
```




